export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILED = 'FETCH_IMAGES_FAILED';
export const SELECT_IMAGE = 'SELECT_IMAGE';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const BEGIN_AJAX_ERROR = 'BEGIN_AJAX_ERROR';

